fix: some bag fix
Romaleso261981/vite-fsd-template pull request #40
Opened 2023-12-24 13:52 UTC by Romaleso261981

2023-12-29 08:32 UTC, suveiko commented on src/app/App.tsx
> +  const setIsRegistered = useSelector(useSelectSetIsRegistered);
create useAppSelector instead of useSelector

![image](https://github.com/Romaleso261981/vite-fsd-template/assets/101190120/b89e7ed4-6d5b-45b2-88bb-25a74e4d4da3)

2023-12-29 08:32 UTC, suveiko commented on src/app/App.tsx
> +    const data = await getFirestoreData<UserData>(DatabasePaths.USERS, 20);
move this logic to redux

2023-12-29 08:32 UTC, suveiko commented on src/features/components/Header/ui/components/UserInfoIcons/UserInfoIcons.tsx
> +export const UserInfoIcons = (props: Props) => {
```suggestion
export const UserInfoIcons = ({ toggleUserShow }: Props) => {
```

2023-12-29 08:32 UTC, suveiko commented on src/features/user/types.ts
> +  users: [] | UserData[];
```suggestion
  users: UserData[];
```

2023-12-29 08:32 UTC, suveiko commented on src/features/user/userSlice.ts
> +      console.log({ ...editedUser });
remove log

2023-12-29 08:32 UTC, suveiko commented on src/pages/Admin/Admin.tsx
> +const Admin = (props: Props) => {
```suggestion
const Admin = ({ dataUsers }: Props) => {
```

2023-12-29 08:32 UTC, suveiko commented on src/pages/Dashboard/ui/components/TableSelection/TableSelection.tsx
> +  const dispach: AppDispatch = useDispatch();
```suggestion
  const dispatch = useAppDispatch();
```

2023-12-29 08:32 UTC, suveiko commented on src/pages/Dashboard/ui/components/TableSelection/TableSelection.tsx
> +              onClick={() => {
create function for this

2023-12-29 08:32 UTC, suveiko commented on src/pages/UserDetail/UserDetail.tsx
> +  const dispach: AppDispatch = useDispatch();
move dispatch to the top of the component and fix naming dispach -> dispatch

2023-12-29 08:32 UTC, suveiko commented on src/pages/UserDetail/UserDetail.tsx
> +              onChange={(e) => handleInputChange('nickName', e.target.value)}
move outside

2023-12-29 08:32 UTC, suveiko commented on src/pages/UserDetail/UserDetail.tsx
> +              onChange={(e) => handleInputChange('rule', e.target.value)}
move outside

2023-12-29 08:32 UTC, suveiko commented on src/pages/UserDetail/UserDetail.tsx
> +              onChange={(e) => handleInputChange('balans', e.target.value)}
move outside

2023-12-29 08:32 UTC, suveiko commented on src/shared/helpers/Redirect.ts
> +export const Redirect = (path: string) => {
why you create this function?

2023-12-29 08:32 UTC, suveiko commented on src/shared/helpers/editUser.ts
> +    console.log(userId, editedUser);
remove log

2024-01-03 07:17 UTC, remadyt requested changes

2024-01-03 07:17 UTC, remadyt commented on src/app/App.tsx
> +  const user = useAppSelector(useSelectUser) ?? null;
move null to useSelectUser

2024-01-03 07:17 UTC, remadyt commented on src/app/App.tsx
> +  // const navigate = useNavigate();
why need navigate?

2024-01-03 07:17 UTC, remadyt commented on src/app/App.tsx
> +              <AuthChecker path="/auth" comp>
use enum for Paths

2024-01-03 07:17 UTC, remadyt commented on src/app/App.tsx
> +                <h1>Ви немаєте права доступу</h1>
transaltes?

2024-01-03 07:17 UTC, remadyt commented on src/app/AuthChecker.tsx
> +// import { auth } from '../integations/firebase';
why its needed?

2024-01-03 07:17 UTC, remadyt commented on src/app/AuthChecker.tsx
> +  }, []); // eslint-disable-line react-hooks/exhaustive-deps
remove eslint errors

2024-01-03 07:17 UTC, remadyt commented on src/features/auth/authSlice.ts
> +        localStorage.setItem('user', JSON.stringify(existedUser));
create helper function for this

2024-01-03 07:17 UTC, remadyt commented on src/features/auth/authSlice.ts
> +      await addDoc(collectionRef, {
why its needed?

2024-01-03 07:17 UTC, remadyt commented on src/features/components/Header/HeaderMegaMenu.module.css
> +  padding-right: 50px;
padding: 0 50px

2024-01-03 07:17 UTC, remadyt commented on src/features/components/Header/index.tsx
> +    setIsUserShow(!isUserShow);
prev => !prev

2024-01-03 07:17 UTC, remadyt commented on src/features/components/Header/ui/components/UserInfoIcons/UserInfoIcons.module.css
> +	color: light-dark(var(--mantine-color-gray-5), var(--mantine-color-dark-3));
add stylelint

2024-01-03 07:17 UTC, remadyt commented on src/features/components/Header/ui/components/UserInfoIcons/UserInfoIcons.tsx
> +import { getCurrentUser } from '../../../../../../shared/helpers/getCurrentUser';
use global paths

2024-01-03 07:17 UTC, remadyt commented on src/features/components/Header/ui/components/UserInfoIcons/UserInfoIcons.tsx
> +    navigate('/auth');
if request error?

2024-01-03 07:17 UTC, remadyt commented on src/features/user/userSlice.ts
> +        throw new Error('Відсутній ідентифікатор користувача.');
its bad ux, add notification

2024-01-03 07:17 UTC, remadyt commented on src/features/user/userSlice.ts
> +      const data = await getFirestoreData<UserData>(DatabasePaths.USERS, 20);
u take only 20? and implement deleting user not needed

2024-01-03 07:17 UTC, remadyt commented on src/pages/Auth/ui/components/AuthenticationTitle/Auth.tsx
>        case 'EnterOTP':
use enum for cases

2024-01-03 07:17 UTC, remadyt commented on src/pages/Auth/ui/components/AuthenticationTitle/components/EnterNickName/EnterNickName.tsx
> +      <form onSubmit={form.onSubmit((value) => handleFormSubmit(value))}>
form.onSubmit(handleFormSubmit)

2024-01-03 07:17 UTC, remadyt commented on src/pages/Auth/ui/components/AuthenticationTitle/components/EnterNickName/EnterNickName.tsx
> +    form.setValues({ nickName: '' });
why its needed?

2024-01-03 07:17 UTC, remadyt commented on src/shared/helpers/editUser.ts
> +    console.log(`error ${error}`);
add notification instead of console log

2024-01-03 07:17 UTC, remadyt commented on src/shared/helpers/editUser.ts
> +    // eslint-disable-next-line no-console
remove eslint error here and all such places

2024-01-06 10:18 UTC, merged