Feature user detail
Romaleso261981/vite-fsd-template pull request #44
Opened 2024-01-09 13:35 UTC by Romaleso261981

2024-01-10 16:12 UTC, remadyt requested changes

2024-01-10 16:12 UTC, remadyt commented on src/app/App.tsx
>  const App: React.FC = () => {
use FC instead of React.FC here and all such places

2024-01-10 16:12 UTC, remadyt commented on src/features/auth/authSlice.ts
> +      const data = await getFirestoreData<User>(DatabasePaths.USERS, 20);
why u check only 20 user?

2024-01-10 16:12 UTC, remadyt commented on src/features/auth/authSlice.ts
> +        localStorage.setItem('user', JSON.stringify(existedUser));
move to helpers

2024-01-10 16:12 UTC, remadyt commented on src/features/auth/authSlice.ts
> +      window.location.href = '/';
recator, do not paths with location, use navigate

2024-01-10 16:12 UTC, remadyt commented on src/features/components/Header/ui/components/NavbarLink/NavbarLink.tsx
> +    localStorage.removeItem('code');
whats is code?

2024-01-10 16:12 UTC, remadyt commented on src/features/components/Header/ui/components/NavbarLink/NavbarLink.tsx
>      navigate('/auth');
if logout have erorr, navigate not needed, move navigate logic to try block

2024-01-10 16:12 UTC, remadyt commented on src/features/user/userSlice.ts
> +        await hookEditUser({ id, user });
use more informative name,

2024-01-10 16:12 UTC, remadyt commented on src/features/user/userSlice.ts
> +      if (id) {
```
if(!id) {
  return
}

// some logic
```

2024-01-10 16:12 UTC, remadyt commented on src/pages/Admin/Admin.tsx
> +  if (userData?.rule !== 'admin') {
isAdmin helper here?

2024-01-10 16:12 UTC, remadyt commented on src/pages/Admin/ui/components/TableSelection/TableSelection.module.css
> +	border: none;
why u not use stylelint?

2024-01-10 16:12 UTC, remadyt commented on src/pages/Admin/ui/components/TableSelection/TableSelection.tsx
> +    navigate(`/admin/${id}`);
use Enum for '/admin'

2024-01-10 16:12 UTC, remadyt commented on src/pages/Admin/ui/components/TableSelection/TableSelection.tsx
> +            (sortDirection === Direction.ASC ? '↑' : '↓')}
move to const and reuse

2024-01-10 16:12 UTC, remadyt commented on src/pages/Auth/ui/components/GithubButton/GithubButton.tsx
> +  // const clientId = import.meta.env.VITE_clientId;
remove commented code

2024-01-10 16:12 UTC, remadyt commented on src/pages/Auth/ui/components/GithubButton/GithubButton.tsx
> +      leftSection={<GithubIcon style={{ width: '1rem', height: '1rem' }} />}
do not use inline styles

2024-01-10 16:12 UTC, remadyt commented on src/pages/Userdetails/Userdetails.module.css
> +	display: flex;
prettify all css files

2024-01-10 16:12 UTC, remadyt commented on src/pages/Userdetails/Userdetails.tsx
> +    if (id) {
if !id return

2024-01-10 16:12 UTC, remadyt commented on src/pages/Userdetails/Userdetails.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
do not ignore eslit error, fix

2024-01-10 16:12 UTC, remadyt commented on src/pages/Userdetails/Userdetails.tsx
> +      notifications.show({
move notify to try block, if request failed u not shown succes notif

2024-01-10 16:12 UTC, remadyt commented on src/pages/Userdetails/Userdetails.tsx
> +        title: 'success',
translate?

2024-01-10 16:12 UTC, remadyt commented on src/pages/Userdetails/Userdetails.tsx
> +            onClick={() => navigate('/admin')}
use Navlink for navigating

2024-01-10 16:12 UTC, remadyt commented on src/shared/helpers/getUserById.ts
> +    const docSnapshot = await getDoc(docRef);
create helper

2024-01-10 16:12 UTC, remadyt commented on src/shared/helpers/getUserById.ts
> +    notifications.show({
create common function for handle errors

2024-01-10 16:12 UTC, remadyt commented on src/shared/helpers/isAdmin.ts
> +export const isAdmin = (data: User | null) => {
refactor to useAdmin (take user data from useSelector)

2024-01-10 16:12 UTC, remadyt commented on src/shared/types/enums.ts
> +  USER = '/admin/:id',
incorrect name

2024-01-12 12:32 UTC, AdammmVV commented on src/features/auth/authSlice.ts
>        state.userData = payload!;
don't use `" ! "` create types for think ( `payload` )

2024-01-12 12:32 UTC, AdammmVV commented on src/features/auth/authSlice.ts
> +      state.userData = payload!;
don't use `" ! "` create types for think ( `payload` )

2024-01-12 12:32 UTC, AdammmVV commented on src/features/auth/authSlice.ts
> +      state.userData = payload!;
don't use `" ! "` create types for think ( `payload` )

2024-01-12 12:32 UTC, AdammmVV commented on src/pages/Userdetails/Userdetails.tsx
> +      <form className={styles.formWrapper}>
use onSubmit

2024-01-12 12:32 UTC, AdammmVV commented on src/pages/Userdetails/Userdetails.tsx
> +          <Button
button type "submit"

2024-01-12 12:32 UTC, AdammmVV commented on src/pages/Userdetails/Userdetails.tsx
> +          placeholder="your@email.com"
placeholder does not match

2024-01-12 12:32 UTC, AdammmVV commented on src/pages/Userdetails/Userdetails.tsx
> +          placeholder="your@email.com"
placeholder does not match

2024-01-12 12:32 UTC, AdammmVV commented on src/features/auth/authSlice.ts
>  import { AuthState, User } from '../../shared/types/Types';
why don't you use absolute imports?

2025-02-19 11:38 UTC, merged